### ISSUE TITLE
Would it be ok to include this great control on the Unity UI Extensions project?

### ISSUE THREAD

**Issue by SimonDarksideJ** [sinbad/UnityRecyclingListView#2]
I run a small project called the UnityUIExtensions which contains a lot of community provided UI scripts for devs
https://bitbucket.org/UnityUIExtensions/unity-ui-extensions

It's all open source and free for all, although we also support having links for individual contributions.

Would you be open to having this control included in the set, you can either send a PR yourself, or I can simply pull and update it within the UI Extensions framework.

Thoughts?

**Comment by sinbad** [comment]
It's MIT so yeah you're free to do that so long as you include the LICENSE file as well. Bear in mind though, there are a couple of edge cases I want to come back to so it'll likely get some updates over time, you'll need to pull in a new version every so often on that basis if you want those. I don't really want to have to remember to send PRs to anyone who might use this in their collections, so will leave it to people who want to use it to pull that in themselves.

Since cross-linking is kind of a pain between BB & GH I recommend using `git subtree` to quickly flatten the contents into a folder on your project while maintaining the commit/author history.
